---
title: "Assignment03"
author: "Odiche Nwabuikwu"
date: "2/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_package, message = FALSE}

library(tidyverse)
library(waffle)
library(urbnthemes)
set_urbn_defaults(style = "print")

```


```{r import_data, message = FALSE}

sex <- read_csv('data/EducationDataPortal_02.07.2020_sex.csv')
study <- read_csv('data/EducationDataPortal_02.07.2020_level_of_study.csv')
inst <- read_csv('data/EducationDataPortal_02.13.2020_institutions.csv')
ftpt <- read_csv('data/EducationDataPortal_02.12.2020_ftpt.csv')
```

```{r clean_data, warning = FALSE, message = FALSE}

# ftpt
# reshape 
ftpt <- pivot_wider(data = ftpt, names_from = ftpt, values_from = retention_rate)

# remove missing values AND make states categorical vars
ftpt <- ftpt %>%
  filter(!is.na('state_name'), !is.na(`Full-time`), !is.na(`Part-time`)) %>%
  mutate(state_name = factor(state_name, levels = c("California", "Florida", "New York",
                                                    "Pennsylvania", "Texas"))) %>%
  select(-`Part-time`, -Total)

# sex
sex <- sex %>%
  filter(sex != 'Total') %>%
  filter(!is.na(number_applied)) %>%
  select(-number_admitted)

# reshape - num applied
sex <- pivot_wider(data = sex, names_from = sex, 
                   values_from = number_applied)


# study
study <- study %>%
  filter(!is.na(enrollment_fall),
                level_of_study != 'Graduate') %>%
  select(-level_of_study)

# inst
# remove character and missing values from percent variable
inst <-inst %>%
  filter(!grepl("[a-z]", inst$lowincome_pct)) %>%
  filter(!is.na(lowincome_pct))

# merge datasets
ed_data <- left_join(ftpt, inst)
ed_data <- full_join(ed_data, sex)
ed_data <- full_join(ed_data, study)


rm(ftpt, inst, sex, study)

```


```{r viz_1, message = FALSE}

## 1st graph

# collapse by state and year to get mean retention rates
ftpt <- ed_data %>%
  group_by(state_name, year) %>%
  summarize(reten_full = mean(`Full-time`, na.rm = TRUE))

# line graph
ggplot(data = ftpt) +
  geom_line(mapping = aes(x = year, y = `reten_full`, color = state_name)) +
  geom_point(mapping = aes(x = year, y = `reten_full`, color = state_name), show.legend = FALSE) +
  scale_x_continuous(breaks = seq(2003, 2013, 1), limits = c(2003, 2013)) +
  labs(title = "AVERAGE RETENTION RATES AT U.S. TERTIARY INSTITUTIONS FROM 2003-2013",
       subtitle = "States Show Varying Retention Rates After the 2008 Recession",
       caption = "Source: Urban Institute",
       x = "Year",
       y = "Full-Time Rention Rates") 
```

```{r include=FALSE}
rm(ftpt)
```


```{r viz_2, message = FALSE}
# 2nd graph

sex <- ed_data %>%
  filter(year %in% c(2006:2010)) %>%
  select(-`Full-time`, -enrollment_fall, -state_abbr, -lowincome_pct) %>%
  pivot_longer(cols = c(-year, -unitid, -inst_name, -state_name),
               names_to = "sex", values_to = "number_applied") %>%
  filter(!is.na(number_applied)) %>%
  distinct() %>%
  filter(state_name %in% c("California"))

# group by sex and year to make bar chart
sex <- sex %>%
  group_by(year, sex) %>%
summarize(count_app = mean(number_applied))
  

ggplot(data = sex,
       mapping = aes(fill = sex, y = count_app, x = factor(year))) +
  geom_bar(position = "stack", stat="identity") +
  scale_y_continuous(breaks = seq(0, 8000, 2000), lim = c(0, 7000)) +
  labs(title = 
        paste("UNDERGRADUATE APPLICATIONS TO CALIFORNIA",
        "UNIVERISITIES FROM 2006-2010"),
       subtitle = "Gender application patterns stay constant during the 2008 Financial Crisis",
       caption = "Source: Urban Institute",
       x = "Year",
       y = "Number of Applications") 

```

```{r include=FALSE}
rm(sex)
```

```{r viz_3, message = FALSE}
# 3rd graph

study <- ed_data %>%
  filter(!is.na(enrollment_fall),
         year == 2007)
  
study %>%
  group_by(state_name) %>%
  summarize(enrol = sum(enrollment_fall)) %>%
  ggplot(aes(fill = state_name, values = enrol)) +
  geom_waffle(n_rows = 10, size = 1, colour = "white", 
              flip = TRUE, make_proportional = TRUE) +
  coord_equal() +
  scale_fill_manual(name = "State", 
                    values = c("#1696d2", "#fdbf11", "#55b748", "#000000", "#ec008b")) +
  theme_void() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "2007 UNDERGRADUATE FALL ENROLLMENT",
       subtitle = "Each square represents approximately 61,000 students",
       caption = "Source: Urban Institute") 
```


```{r include=FALSE}
rm(study)
```
